pipeline:
  build:
    image: node
    commands:
      - node --version
      - npm ci
      - rm src/lib/data.json && wget -O src/lib/data.json https://data.prgblockweek.com/23/index.json
      - npm run build
    when:
      branch: [dev]

  deploy_dev:
    image: rclone/rclone
    commands:
      - 'rclone sync build/ :sftp:dev/ --sftp-host frontier.gwei.cz --sftp-user pbw-deploy --sftp-port 2022 --sftp-pass $RCLONE_PASS -v'
    secrets: [RCLONE_PASS]
    when:
      branch: [dev]

  build_mirror:
    image: node
    commands:
      - node --version
      - npm ci
      - rm src/lib/data.json && wget -O src/lib/data.json https://mirror.data.prgblockweek.com/23/index.json
      - npm run build
    when:
      branch: [main]

  deploy_mirror:
    image: rclone/rclone
    commands:
      - 'rclone sync build/ :sftp:production/ --sftp-host frontier.gwei.cz --sftp-user pbw-deploy --sftp-port 2022 --sftp-pass $RCLONE_PASS -v'
    secrets: [RCLONE_PASS]
    when:
      branch: [main]
